name: itrust_server
description: ITrust server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  # third party
  args: ^2.3.2
  collection: ^1.17.1
  dart_jsonwebtoken: ^2.7.1
  envied: ^0.3.0
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  mapster: ^0.1.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.7

  # git repo
  mediatr:
    git:
      url: https://github.com/bytes7bytes7/dart_mediatr.git
      ref: remove_either_dart

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  http: ^0.13.5
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0
  lints: ^2.0.1
  shelf_router_generator: ^1.0.5
  test: ^1.22.2
