name: itrust_server
description: ITrust server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.1
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.7.1
  envied: ^0.3.0
  equatable: ^2.0.5
  fluent_validation:
    git:
      url: https://github.com/bytes7bytes7/fluent_validation
      ref: "e8406b7"
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  mapster: ^0.3.2
  mediator:
    git:
      url: https://github.com/bytes7bytes7/mediator
      ref: "0fb783a"
  path: ^1.8.3
  problem_details: ^0.0.2
  rxdart: ^0.27.7
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.4
  stack_trace: ^1.11.0
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  http: ^0.13.5
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lints: ^2.0.1
  shelf_router_generator: ^1.0.5
  test: ^1.23.1
