name: itrust_server
description: ITrust server.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.2
  collection: ^1.17.1
  logging: ^1.1.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.22.2
